function(dtm2020_apply_strict_fp_flags target_name)
  if(MSVC)
    target_compile_options(${target_name} PRIVATE /fp:precise)
  else()
    target_compile_options(${target_name} PRIVATE -ffp-contract=off)
  endif()
endfunction()

function(dtm2020_apply_runtime_flags target_name)
  if(DTM2020_ENABLE_PROFILE)
    if(MSVC)
      target_compile_options(${target_name} PRIVATE /O2 /Zi)
    else()
      target_compile_options(${target_name} PRIVATE -O3 -g -fno-omit-frame-pointer)
    endif()
  endif()

  if(DTM2020_SANITIZER STREQUAL "address")
    if(MSVC)
      target_compile_options(${target_name} PRIVATE /fsanitize=address /Zi)
      target_link_options(${target_name} PRIVATE /fsanitize=address)
    else()
      target_compile_options(${target_name} PRIVATE -fsanitize=address -fno-omit-frame-pointer -g)
      target_link_options(${target_name} PRIVATE -fsanitize=address)
    endif()
  elseif(DTM2020_SANITIZER STREQUAL "undefined")
    if(NOT MSVC)
      target_compile_options(${target_name} PRIVATE -fsanitize=undefined -fno-omit-frame-pointer -g)
      target_link_options(${target_name} PRIVATE -fsanitize=undefined)
    endif()
  elseif(DTM2020_SANITIZER STREQUAL "thread")
    if(NOT MSVC)
      target_compile_options(${target_name} PRIVATE -fsanitize=thread -fno-omit-frame-pointer -g)
      target_link_options(${target_name} PRIVATE -fsanitize=thread)
    endif()
  endif()
endfunction()
